language: php
php:
  - '7.3'
  - '7.4'

branches:
  only:
    - master

install:
  - composer install --dev

script:
  - composer validate
  - composer security
  - composer check-style
  - composer check-static-analyze
  - composer unit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v