language: php
php:
  - '7.3'
  - '7.4'

branches:
  only:
    - master

install:
  - composer install --dev

script:
  - composer validate
  - vendor/bin/security-checker security:check
  - vendor/bin/phpcs --ignore-annotations --standard=PSR12 src tests
  - vendor/bin/phpcf tests src && vendor/bin/phpstan analyse --level=max src tests
  - vendor/bin/phpunit
  - vendor/bin/php-coverage-checker build/logs/clover.xml 100

after_success:
  - travis_retry php vendor/bin/php-coveralls -v